version: "3.7"
services:
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '5ecur3'
    networks:
      - zarusnet

volumes:
  mysql:

networks:
  zarusnet:

