# taps {{{

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
# tap "adoptopenjdk/openjdk"

# }}}

# formulaes {{{

# brew "bash"
# brew "curl"
# brew "git"
# brew "gpg"
# brew "neovim"
# brew "tmux"
# brew "tree"
# brew "unrar"
# brew "vim"
# brew "zsh"
# brew "fzf"
# brew "findutils"
# brew "youtube-dl"
# brew "gnu-tar"
# brew "jq"
# brew "freetype"
# brew "coreutils"
# brew "nodejs"
# brew "htop"
# brew "ffmpeg" # convert between different video formact

## kubernetes
# brew "kubectx"

# completions {{{

#brew "brew-cask-completion"
#brew "cargo-completion"
#brew "rustc-completion"
#brew "zsh-completions"

# }}}

# }}}

# casks {{{

# cask "adobe-acrobat-reader"
# cask "appcleaner"
# cask "brave-browser"
# cask "iterm2"
# cask "transmission"
# cask "adoptopenjdk"
# cask "multipass"
# cask "virtualbox"
# cask "virtualbox-extension-pack"
# cask "emacs"
# cask "spectacle"
# cask "vlc"
# cask "visual-studio-code"
# cask "balenaetcher"
# cask "kodi"
# cask "jaxx-liberty"
# cask "docker"
# cask "mpv"

# fonts {{{

cask "font-anonymous-pro"
cask "font-awesome-terminal-fonts"
cask "font-clear-sans"
cask "font-hack-nerd-font"
cask "font-inconsolata"
cask "font-input"
cask "font-meslo-lg"
cask "font-nixie-one"
cask "font-office-code-pro"
cask "font-source-code-pro"
cask "font-source-sans-pro"
cask "font-ubuntu"

# }}}

# }}}
