version: '3'

services:
  gitea:
    image: gitea/gitea:latest
    volumes:
      - ./volumes/gitea:/data
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - mariadb
    restart: always
  mariadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=db_5ecur3
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=db_5ecur3
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
