version: '3'

services:
  db:
    container_name: mysql_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
        #- ./mysql.cnf:/etc/mysql/conf.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'changeme'
