version: "3.7"

services:

  janus:
    container_name: janus
    image: janusgraph/janusgraph:latest
    ports:
      - 8182:8182
      - 8184:8184
    depends_on:
      - cass1
      - elastic1
    env_file:
      - db/janus/janus.env
    # environment:
    #   - JANUS_STORAGE_BACKEND=cql
    #   - JANUS_STORAGE_HOSTNAME=cass1
    #   - JANUS_INDEXES=elastic1
    #   - JANUS_INDEX_HOSTNAME=elastic1
    #   - JANUS_GREMLIN_CHANNELIZER=org.apache.tinkerpop.gremlin.server.channel.HttpChannelizer
    networks:
      - zarusnet

  cass1:
    container_name: cass1
    image: cassandra:latest
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    # restart: always
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    env_file:
      - db/cassandra/cass.env
    # environment:
    #   - CASSANDRA_START_RPC=true
    #   - CASSANDRA_CLUSTER_NAME=cluster1
    #   - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    #   - CASSANDRA_DC=naeast
    #   - CASSANDRA_SEEDS=cass1
    volumes:
      - cass1:/var/lib/cassandra/data
    networks:
      - zarusnet

  elastic1:
    container_name: elastic1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    environment:
      - discovery.type=single-node
      - cluster.name=cluster1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elastic1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - zarusnet

  iris:
    container_name: iris
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - APP_NAME="Iris - cup of git"
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_NAME=iris
      - DB_USER=iris
      - DB_PASSWD=db_admin
    # restart: always
    ports:
      - 3000:3000
      - 222:22
    volumes:
      - iris:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - zarusnet
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    # restart: always
    environment:
      - POSTGRES_PASSWORD=db_admin
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - zarusnet

  adminer:
    container_name: adminer
    image: adminer
    # restart: always
    ports:
      - 8000:8080
    networks:
      - zarusnet

volumes:
  iris:
  postgres:
  cass1:
  elastic1:

networks:
  zarusnet:
