apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-agile
  labels:
    app: gitea
    tier: agile
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: agile
  template:
    metadata:
      labels:
        tier: agile
    spec:
      containers:
        - name: gitea
          image: gitea/gitea
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: "pwd"

