apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pulsar
  labels:
    app: pulsar
    tier: middle
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: broker
  template:
    metadata:
      labels:
        tier: middle
    spec:
      containers:
        - name: pulsar
          image: apachepulsar/pulsar
