# Executes commands at the start of an interactive session.

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# path exports {{{

# export PATH=/usr/local/sbin:$PATH
export PATH=$PATH:/snap/bin
export PATH=$HOME/.cargo/bin:$PATH
export PATH="$PATH:$(go env GOROOT)/misc/wasm"

export GREP_OPTIONS='--color=auto'
export MANPAGER="less -X" # Don’t clear the screen after quitting a manual page
export EDITOR="vim"

# }}}

# fzf configuration {{{

bindkey -M viins '^R' history-incremental-search-backward
bindkey -M vicmd '^R' history-incremental-search-backward
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# fzf ignore directories
# Add any other directories you want ignored with -o -name directory_name -prune
# export FZF_DEFAULT_COMMAND='find . -name .git -prune -o -name node_modules -prune -o -name coverage -prune -o -name tmp -prune -o -type f -print'

# }}}

# os specific {{{

# if [[ "$OSTYPE" == "linux-gnu" ]]; then
  # echo "linux"
# elif [[ "$OSTYPE" == "darwin"* ]]; then
#   echo "mac => exports done."
# else
#   echo "no exports"
# fi

# }}}

# aliases {{{

# commands
alias c='clear'
alias x='exit'
alias lg='ls -la1 --group-directories-first'
alias cpi='cp -iv'
alias h='history'
alias j='jobs -l'
alias mk='mkdir -p'
alias mv='mv -iv'
alias path='echo -e ${PATH//:/\\n}'
alias rm='rm -i'
alias rmf='rm -rf'
alias which='type -a'

# vim
alias vim='nvim'
alias neorc='vim ~/.config/nvim/init.vim'
alias vimrc='vim ~/.vimrc'

# config files
alias rel='source ~/.zshrc'
alias relb='source ~/.bashrc'
alias zrc='vim ~/.zshrc'
alias bashrc='vim ~/.bashrc'
alias bashp='vim ~/.bash_profile'
alias aliases='vim ~/.bash_aliases'
alias gitrc='vim ~/.gitconfig'
alias epath='vim /etc/paths.d'
alias path='echo "${PATH//:/\n}"'

# networking
alias ping='ping -c 4'
alias zt='zerotier-cli'

# common
alias grep='grep -n'
alias pre='open -a Preview'
alias text='open -a TextEdit'
alias mup='brew update && brew upgrade && brew cleanup && brew doctor'
alias lup='sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y && sudo apt autoclean'

# docker
alias dk='docker'
alias dke='docker exec'
alias dc='docker-compose'
alias dra='docker rm -f $(docker ps -aq)'

# kubernetes
alias kube='microk8s kubectl'
alias m8='microk8s'
alias kubetoken='token=$(microk8s.kubectl -n kube-system get secret | grep default-token | cut -d " " -f1) && microk8s.kubectl -n kube-system describe secret $token'

# rust lang
alias cb='cargo fmt; cargo build'
alias cf='cargo fmt'
alias co='cargo'
alias cr='cargo run'
alias ct='cargo test'
alias cw='cargo watch -x run'
alias ru='rustup'
alias cwatch='cargo watch -i .gitignore -i "pkg/*" -s "wasm-pack build"'

# python
alias python='python3'
alias pip='pip3'

# web assembly
alias wp='wasm-pack'

# multipass
alias mp='multipass'

# }}}
