version: '3'

services:
  cassdb:
    container_name: cassdb
    image: cassandra:latest
    command: bash -c "sleep 5 && echo '--> Pausing ...' && /docker-entrypoint.sh cassandra -f"
    ports:
      - 9042:9042
    # expose:
    #   - 7000:7000
    #   - 7001:7001
    #   - 7199:7199
    #   - 9042:9042
    #   - 9160:9160
    env_file:
      - ./config/dev.cass.env
    volumes:
      - cassdb:/var/lib/cassandra/data
    networks:
      - zarusnet

volumes:
  cassdb:

networks:
  zarusnet:

