version: '3'

services:

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    env_file:
      - ./config/dev.mysql.env
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - zarusnet

  # phpmyadmin:
  #   container_name: phpmyadmin
  #   depends_on:
  #     - mysql
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - '9000:80'
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: root
  #   networks:
  #     - zarusnet

volumes:
  mysql:

networks:
  zarusnet:

