version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - ./config/dev.postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - zarusnet

volumes:
  postgres:

networks:
  zarusnet:
