version: "3.7"
services:
  janus:
    container_name: janus
    image: janusgraph/janusgraph:latest
    ports:
      - 8182:8182
      - 8184:8184
    depends_on:
      - cass1
      - elastic1
    env_file:
      - janus.env
    # environment:
    #   - JANUS_STORAGE_BACKEND=cql
    #   - JANUS_STORAGE_HOSTNAME=cass1
    #   - JANUS_INDEXES=elastic1
    #   - JANUS_INDEX_HOSTNAME=elastic1
    #   - JANUS_GREMLIN_CHANNELIZER=org.apache.tinkerpop.gremlin.server.channel.HttpChannelizer
    networks:
      - zarusnet

  cass1:
    container_name: cass1
    image: cassandra:latest
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    # restart: always
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    env_file:
      - cass.env
    # environment:
    #   - CASSANDRA_START_RPC=true
    #   - CASSANDRA_CLUSTER_NAME=cluster1
    #   - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    #   - CASSANDRA_DC=naeast
    #   - CASSANDRA_SEEDS=cass1
    volumes:
      - cass1:/var/lib/cassandra/data
    networks:
      - zarusnet

  elastic1:
    container_name: elastic1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    environment:
      - discovery.type=single-node
      - cluster.name=cluster1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elastic1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - zarusnet

volumes:
  cass1:
  elastic1:

networks:
  zarusnet:
