version: "3.7"

services:

  # pulsar:
  #   container_name: pulsar
  #
  #  janus:
  #    container_name: graph1
  #    image: janusgraph/janusgraph:latest
  #    ports:
  #      - 8182:8182
  #      - 8184:8184
  #    depends_on:
  #      - cas1
  #      - elastic1
  #    environment:
  #      - JANUS_STORAGE_BACKEND=cql
  #      - JANUS_STORAGE_HOSTNAME=cas1
  #      - JANUS_INDEXES=elastic1
  #      - JANUS_INDEX_HOSTNAME=es1
  #      - JANUS_GREMLIN_CHANNELIZER=org.apache.tinkerpop.gremlin.server.channel.HttpChannelizer

  cass:
    container_name: cass
    image: cassandra:latest
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    restart: always
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=cluster1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=naeast
      - CASSANDRA_SEEDS=cass
    volumes:
      - cass:/var/lib/cassandra/data
    networks:
      - zarusnet

#   elastic:
#     container_name: elastic
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
#     environment:
#       - discovery.type=single-node
#       - cluster.name=cluster1
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     volumes:
#       - elastic:/usr/share/elasticsearch/data
#     networks:
#       - zarusnet
#     ports:
#       - 9200:9200

volumes:
  # pulsar:
  cass:
  # elastic:

networks:
  zarusnet:
