version: '3'

services:

  cas1:
    container_name: cas1
    image: cassandra:latest
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    restart: always
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    env_file:
      - cassandra/cass.env
    volumes:
      - ./data/cassandra/cas1:/var/lib/cassandra/data

